sudo: required

services:
  - docker

before_install:
  - docker build -t diksha/docker-react -f Dockerfile.dev .

script:
  - docker run  diksha/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-677933751647"
  bucket_path: "docker-react"
  on:
    branch: master